version: "3.8"

services:

  flask_backend:
    image: nithinsibi/flaskapp-flask_backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"

  nginx:
    image: nithinsibi/flaskapp-nginx:latest
    depends_on:
      - flask_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"

